# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a5f56fe99ed6c77a01045e5237b4b9a873f6df749dced77cf493d4acf513bde953469823b76163f7406d0527ef6b2ab2d72b9cf0ed9bde3c125cb4cabc047f

test:
  secret_key_base: e9b9b6e662b24208a5563367d2f1a696457dbeab6dc4e4d993b99723ed01dce005b260c4ae2c8add2e6c25f4679fe370f82b2ef6ef8c1eebc406bf16fc1c7f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
